# Generated by Django 5.1.7 on 2025-03-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashina', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='car_ratting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mashina.car'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashina.client'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mashina.company'),
        ),
    ]
